# version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: escriptorium/Dockerfile.custom
    image: escriptorium-custom:latest
    volumes:
      - ./app:/usr/src/app
      - ./front/dist:/usr/src/app/front
      - ./app/config/providers.yml:/usr/src/app/config/providers.yml:ro
    restart: always

  channelserver:
    image: escriptorium-custom:latest
    restart: always

  db:
    restart: always

  redis:
    restart: always

  elasticsearch:
    restart: always
    build:
      context: ./elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  nginx:
    restart: always
    ports:
      - "80:80"

  flower:
    restart: always

  celery-main:
    image: escriptorium-custom:latest
    volumes:
      - ./app:/usr/src/app
      - ./front/dist:/usr/src/app/front
      - ./app/config/providers.yml:/usr/src/app/config/providers.yml:ro

    restart: always

  celery-low-priority:
    image: escriptorium-custom:latest
    restart: always

  celery-gpu:
    image: escriptorium-custom:latest
    restart: always
