# version: "3.9"

x-app: &app
  build:
    context: ..
    dockerfile: escriptorium/Dockerfile.custom
  image: escriptorium-custom:latest
  env_file: variables.env
  volumes:
    - ./app:/usr/src/app
    - ./app/config/providers.yml:/usr/src/app/config/providers.yml:ro
    - ../yjxz:/usr/src/yjxz

services:
  web:
    <<: *app
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    restart: always

  channelserver:
    <<: *app
    command: daphne --bind 0.0.0.0 --port 5000 -v 1 escriptorium.asgi:application
    restart: always

  db:
    restart: always

  redis:
    restart: always

  elasticsearch:
    restart: always
    build:
      context: ./elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

  nginx:
    restart: always
    ports:
      - "80:80"

  flower:
    restart: always

  celery-main:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q default -c ${CELERY_MAIN_CONC:-10} --max-tasks-per-child=10"
    restart: always
    volumes:
      - ./front/dist:/usr/src/app/front

  celery-live:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q live -c ${CELERY_LIVE_CONC:-10} --max-tasks-per-child=10"
    restart: always

  celery-low-priority:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q low-priority -c ${CELERY_LOW_CONC:-10} --max-tasks-per-child=10"
    restart: always

  celery-gpu:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q gpu -c 1 --max-tasks-per-child=1"
    restart: always
