# version: "3.9"
x-app-build: &app-build
  context: ..
  dockerfile: escriptorium-chinese/Dockerfile.custom


x-app: &app
  image: escriptorium-custom:latest
  env_file: variables.env
  volumes:
    - ./app/config/providers.yml:/usr/src/app/config/providers.yml:ro
    - ../yjxz:/usr/src/yjxz

services:
  web:
    <<: *app
    build: *app-build
    command: uwsgi --ini /usr/src/app/uwsgi.ini
    restart: always
    
# daphne 命令的目录路径，官方的目录路径是escriptorium, 新版改成了escriptorium_chinese，
# 克隆以后应该改成escriptorium, 跟daphne的参数符合.
  channelserver:
    <<: *app
    command: daphne --bind 0.0.0.0 --port 5000 -v 1 escriptorium.asgi:application
    restart: always

  db:
    restart: always

  redis:
    restart: always

  elasticsearch:
    restart: always
    build:
      context: ./elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m" # wsl内存问题，在其他机器上可以调高到512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata:/usr/share/elasticsearch/data

  nginx:
    restart: always
    ports:
      - "80:80"

  flower:
    restart: always

  celery-main:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q default -c ${CELERY_MAIN_CONC:-10} --max-tasks-per-child=10"
    restart: always
  #  volumes:
  #    - ./front/dist:/usr/src/app/front

  celery-live:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q live -c ${CELERY_LIVE_CONC:-10} --max-tasks-per-child=10"
    restart: always

  celery-low-priority:
    <<: *app
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q low-priority -c ${CELERY_LOW_CONC:-10} --max-tasks-per-child=10"
    restart: always

  celery-gpu:
    <<: *app
    shm_size: '3gb'
    runtime: nvidia
    environment:
      - KRAKEN_TRAINING_DEVICE=cuda:0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: "celery -A escriptorium worker -l INFO -E -Ofair --prefetch-multiplier 1 -Q gpu -c 1 --max-tasks-per-child=1"
    restart: always
