# Generated by Django 4.2.23 on 2025-10-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='librarycatalog',
            new_name='knowledge_l_title_3f6f86_idx',
            old_name='knowledge_l_title_78a3f8_idx',
        ),
        migrations.RenameIndex(
            model_name='librarycatalog',
            new_name='knowledge_l_collect_922430_idx',
            old_name='knowledge_l_collect_0a1cb9_idx',
        ),
        migrations.RenameIndex(
            model_name='librarycatalog',
            new_name='knowledge_l_call_nu_f99802_idx',
            old_name='knowledge_l_call_n_715689_idx',
        ),
        migrations.RenameIndex(
            model_name='placereference',
            new_name='knowledge_p_standar_6adf35_idx',
            old_name='knowledge_p_standar_365fa4_idx',
        ),
        migrations.RenameIndex(
            model_name='placereference',
            new_name='knowledge_p_dynasty_bac4a6_idx',
            old_name='knowledge_p_dynasty_51f7c1_idx',
        ),
    ]
