# Generated by Django 4.2.23 on 2025-10-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_erareference_personreference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='erareference',
            new_name='knowledge_e_era_nam_abd30a_idx',
            old_name='knowledge_e_era_nam_06782d_idx',
        ),
        migrations.RenameIndex(
            model_name='erareference',
            new_name='knowledge_e_dynasty_37bf30_idx',
            old_name='knowledge_e_dynasty_5a6c85_idx',
        ),
        migrations.RenameIndex(
            model_name='personreference',
            new_name='knowledge_p_name_ecc7ee_idx',
            old_name='knowledge_p_name_6e91df_idx',
        ),
        migrations.RenameIndex(
            model_name='personreference',
            new_name='knowledge_p_dynasty_74ddab_idx',
            old_name='knowledge_p_dynasty_625909_idx',
        ),
    ]
