# Generated by Django 4.2.25 on 2025-10-31 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gazetteer.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='朝代名称')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='起始年')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='结束年')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '朝代',
                'verbose_name_plural': '朝代',
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='实体名称')),
                ('type', models.CharField(choices=[('person', '人物'), ('place', '地点'), ('event', '事件'), ('org', '机构'), ('other', '其他')], max_length=50, verbose_name='实体类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_name', models.CharField(max_length=255, verbose_name='历史地名')),
                ('modern_name', models.CharField(blank=True, max_length=255, verbose_name='现代地名')),
                ('admin_code', models.CharField(blank=True, max_length=100, verbose_name='行政区划代码')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='gazetteer.location', verbose_name='上级行政区')),
            ],
            options={
                'verbose_name': '地理位置',
                'verbose_name_plural': '地理位置',
            },
        ),
        migrations.CreateModel(
            name='Gazetteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='志书名称')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='修志年份')),
                ('compiler', models.CharField(blank=True, max_length=255, verbose_name='修志人')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('full_text', models.TextField(blank=True, verbose_name='全文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dynasty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gazetteer.dynasty', verbose_name='朝代')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gazetteer.location', verbose_name='地点')),
            ],
            options={
                'verbose_name': '方志',
                'verbose_name_plural': '方志',
                'ordering': ['dynasty', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='条目标题')),
                ('content', models.TextField(verbose_name='条目内容')),
                ('source_page', models.IntegerField(blank=True, null=True, verbose_name='原书页码')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OCR可信度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gazetteer.category', verbose_name='分类')),
                ('gazetteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='gazetteer.gazetteer', verbose_name='方志')),
            ],
            options={
                'verbose_name': '知识条目',
                'verbose_name_plural': '知识条目',
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('located_in', '位于'), ('part_of', '属于'), ('related_to', '相关'), ('ancestor_of', '祖先'), ('successor_of', '继任')], max_length=50, verbose_name='关系类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='gazetteer.entity', verbose_name='源实体')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='gazetteer.entity', verbose_name='目标实体')),
            ],
            options={
                'verbose_name': '实体关系',
                'verbose_name_plural': '实体关系',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='entries',
            field=models.ManyToManyField(related_name='entities', to='gazetteer.entry', verbose_name='相关条目'),
        ),
    ]
