# Generated by Django 4.2.20 on 2025-10-20

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_instancesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPassage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(help_text="Sequential order of the passage within the document.")),
                ("raw_text", models.TextField(help_text="Original text content of the passage.")),
                (
                    "normalized_text",
                    models.TextField(
                        blank=True,
                        help_text="Pre-processed text used for embedding generation.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arbitrary metadata such as headings, page numbers or source links.",
                    ),
                ),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        blank=True,
                        help_text="Cached embedding vector for this passage.",
                        null=True,
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="core.document",
                    ),
                ),
                (
                    "document_part",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional page/part reference this passage originates from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="passages",
                        to="core.documentpart",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "order"],
                "unique_together": {("document", "order")},
            },
        ),
        migrations.AddIndex(
            model_name="documentpassage",
            index=models.Index(
                fields=["document", "order"], name="core_docpass_order_idx"
            ),
        ),
    ]
