# Generated by Django 4.2.23 on 2025-10-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_documentpassage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentpassage',
            new_name='core_docume_documen_8127ec_idx',
            old_name='core_docpass_order_idx',
        ),
    ]
